--no-header omits warranty. Patch from Martin von Gagem. Savannah #29307.

diff --git a/test/check_common_fn.in b/test/check_common_fn.in
--- a/test/check_common_fn.in
+++ b/test/check_common_fn.in
@@ -46,74 +46,55 @@ check_result() {
   fi
 }
 
-test_cdinfo() {
+test_common() {
 
-  opts="$1"
-  outfile="$2"
-  rightfile="$3"
+  cmdname="$1"
+  cmd="../src/${cmdname}@EXEEXT@"
+  opts="$2"
+  outfile="$3"
+  rightfile="$4"
 
-  CD_INFO="../src/cd-info@EXEEXT@"
-
-  if [ ! -x ${CD_INFO} ]; then
-    echo "$0: No ${CD_INFO}"
+  if [ ! -x "${cmd}" ]; then
+    echo "$0: No ${cmd}"
     return 1
   fi
 
-  if ${CD_INFO} --no-header ${opts} >${outfile} 2>&1 ; then 
+  cmdline="${cmd}"
+  if "${cmd}" --no-header ${opts} >"${outfile}" 2>&1 ; then 
     if test "@DIFF@" != no; then
-      if @DIFF@ @DIFF_OPTS@ ${outfile} ${rightfile} ; then
-	rm -f $outfile
+      if @DIFF@ @DIFF_OPTS@ "${outfile}" "${rightfile}" ; then
+	rm -f "${outfile}"
 	return 0
       else
 	return 3
       fi
     else
-      echo "$0: No diff(1) or cmp(1) found - cannot test ${CD_INFO}"
-      rm -f $outfile
-      return 77
+      echo "$0: No diff(1) or cmp(1) found - cannot test ${cmdname}"
+      rm -f "${outfile}"
+      return $SKIP_TEST_EXITCODE
     fi
   else
-    echo "$0 failed running: ${CD_INFO} ${opts}"
+    echo "$0 failed running: ${cmdname} ${opts}"
     return 2
   fi
 
+}
+
+test_cdinfo() {
+  test_common cd-info "$@"
 }
 
 test_iso_info() {
+  test_common iso-info "$@"
+}
 
-  opts="$1"
-  outfile="$2"
-  rightfile="$3"
-
-  ISO_INFO="../src/iso-info@EXEEXT@"
-
-  if [ ! -x ${ISO_INFO} ]; then
-    echo "$0: No ${ISO_INFO}"
-    return 1
-  fi
-
-  cmdline="${ISO_INFO} --no-header ${opts}"
-  if $cmdline  >${outfile} 2>&1 ; then 
-    if test "/usr/bin/diff" != no; then
-      if @DIFF@ @DIFF_OPTS@ ${outfile} ${rightfile} ; then
-	rm -f $outfile
-	return 0
-      else
-	return 3
-      fi
-    else
-      echo "$0: No diff(1) or cmp(1 found - cannot test ${ISO_INFO}"
-      rm -f $outfile
-      return 77
-    fi
-  else
-    echo "$0 failed running: $cmdline"
-    return 2
-  fi
-
+test_cd_read() {
+  test_common cd-read "$@"
 }
 
 test_iso_read() {
+
+  # not test_common, as we use an output file not stdout.
 
   opts="$1"
   outfile="$2"
@@ -126,17 +107,17 @@ test_iso_read() {
     return 1
   fi
 
-  if ${ISO_READ} ${opts} -o ${outfile} 2>&1 ; then 
+  if "${ISO_READ}" ${opts} -o "${outfile}" 2>&1 ; then 
     if test "@DIFF@" != no; then
-      if @DIFF@ @DIFF_OPTS@ ${outfile} ${rightfile} ; then
-	rm -f $outfile
+      if @DIFF@ @DIFF_OPTS@ "${outfile}" "${rightfile}" ; then
+	rm -f "${outfile}"
 	return 0
       else
 	return 3
       fi
     else
-      echo "$0: No diff(1) or cmp(1 found - cannot test ${ISO_READ}"
-      rm -f $outfile
+      echo "$0: No diff(1) or cmp(1) found - cannot test ${ISO_READ}"
+      rm -f "${outfile}"
       return 77
     fi
   else
@@ -146,36 +127,31 @@ test_iso_read() {
 
 }
 
-test_cd_read() {
+test_legal_header() {
 
-  opts="$1"
-  outfile="$2"
-  rightfile="$3"
+  cmdname="$1"
+  cmd="../src/${cmdname}@EXEEXT@"
+  opts="$2"
+  outfile="$3"
 
-  CD_READ="../src/cd-read@EXEEXT@"
-
-  if [ ! -x ${CD_READ} ]; then
-    echo "$0: No ${CD_READ}"
-    return 1
+  if test "@GREP@" == no; then
+    echo "$0: No grep(1) found - cannot test ${cmd}."
+    echo "$0: Legal header test skipped."
+    exit $SKIP_TEST_EXITCODE
   fi
-
-  if ${CD_READ} --no-header ${opts} >${outfile} 2>&1 ; then 
-    if test "@DIFF@" != no; then
-      if @DIFF@ @DIFF_OPTS@ ${outfile} ${rightfile} ; then
-	rm -f $outfile
-	return 0
-      else
-	return 3
-      fi
-    else
-      echo "$0: No diff(1) or cmp(1 found - cannot test ${CD_READ}"
-      rm -f $outfile
-      return 77
+  "${cmd}" ${opts} > ${outfile} 2>&1
+  while read line; do
+    if ! grep -q "${line}" ${outfile}; then
+      echo "$0: Legal header test failed due to missing expected line:"
+      echo "  ${line}"
+      echo "$0: Failed command:"
+      echo "  ${cmd} ${opts}"
+      rm -f "${outfile}"
+      exit 4
     fi
-  else
-    echo "$0 failed running: ${CD_READ} ${opts}"
-    return 2
-  fi
+  done < ${srcdir}/check_legal.regex
+  rm -f ${outfile}
+  echo "$0: Legal header of ${cmd} ${opts} ok."
 
 }
 
