check_paranoia.sh.in: Add a more agressive paranoia test.
*version.h*: Include build name in version listings.

diff --git a/test/check_paranoia.sh.in b/test/check_paranoia.sh.in
--- a/test/check_paranoia.sh.in
+++ b/test/check_paranoia.sh.in
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id: check_paranoia.sh.in,v 1.5 2005/01/22 18:54:19 rocky Exp $
+# $Id: check_paranoia.sh.in,v 1.6 2005/01/22 19:39:16 rocky Exp $
 # Compare our cd-paranoia with an installed cdparanoia
 
 if test "@CMP@" != no -a "@BUILD_CD_PARANOIA_TRUE@"X = X ; then
@@ -22,14 +22,25 @@ if test "@CMP@" != no -a "@BUILD_CD_PARANOIA_TRUE@"X = X ; then
     echo "** Under-run correction problem"
     exit 3
   fi
+  # Start out with small jitter
   ../src/cd-paranoia/cd-paranoia -d ./cdda.cue -x 5 -v -r -- "1-"
   mv cdda.raw cdda-jitter.raw
   if @CMP@ ./cdda-jitter.raw ./cdda-good.raw ; then
-    echo "** Jitter correction okay"
+    echo "** Small jitter correction okay"
   else
-    echo "** Jitter correction problem"
+    echo "** Small jitter correction problem"
     exit 3
   fi
+  # A more massive set of failures: underrun + medium jitter
+  ../src/cd-paranoia/cd-paranoia -d ./cdda.cue -x 70 -v -r -- "1-"
+  mv cdda.raw cdda-jitter.raw
+  if @CMP@ ./cdda-jitter.raw ./cdda-good.raw ; then
+    echo "** under-run + jitter correction okay"
+  else
+    echo "** under-run + jitter correction problem"
+    exit 3
+  fi
+  ### FIXME: large jitter is known to fail. Investigate.
   exit 0
 else 
   echo "Don't see libcdio cd-paranoia program. Test skipped."
